### PR TITLE
Rename site parameter to monitoring_site

### LINKED ISSUE #41: Future CentOS 8 support?
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## What are you seeing

"Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Syntax error at 'site' (file: /etc/puppetlabs/code/environments/master/modules_forge/check_mk/manifests/init.pp, line: 13, column: 5) on node some.server.com

## What behaviour did you expect instead

Successful run

## Any additional information you'd like to impart

This module does not currently appear to support CentOS 8, any desire to do so in the future?

thanks in advance!

### PR DESCRIPTION
**Pull request by mmerfort**
#### Pull Request (PR) description
Since “site” is a protected keyword, it may not be used as a parameter name. I renamed it to “monitoring_site”.

#### This Pull Request (PR) fixes the following issues
Fixes #41

### CODE REVIEW

**Comment by tuxmea** [comment]
Looks good to me. Needs major version due to incompatibility

**Review by alexjfisher — CHANGES_REQUESTED** [review]
This is a bug in Puppet 7 fixed in 7.5.0.  See https://tickets.puppetlabs.com/browse/PUP-10929

**Comment by mmerfort** [comment]
> This is a bug in Puppet 7 fixed in 7.5.0. See https://tickets.puppetlabs.com/browse/PUP-10929

Should we still rename it or just wait until 7.5 is out?

**Comment by mmerfort** [comment]
I have added another commit to fix the failing tests, which are broken because of an unrelated issue.

**Comment by mmerfort** [comment]
Sorry, but I'm not interested in supporting Check_MK anymore.

**Pull request closed without merging**
